#!/bin/sh
#description "Salt Minion"

# On latest stable bootstrap script, to set the master ip, pass '-A <ip>' to the script and you're good. A resolvable DNS record or an IP. (cd https://github.com/saltstack/salt/issues/10466)

# The respawn in the minion is known to cause problems
# because if the main minion process dies it has done
# so most likely for a good reason. Uncomment these
# two lines to enable respawn
#respawn
#respawn limit 10 5

# but I can't seem to do it properly with runit (refusing supervision)


# Read configuration variable file if it is present
[ -f /etc/default/$UPSTART_JOB ] && . /etc/default/$UPSTART_JOB

# Activate the virtualenv if defined
[ -f $SALT_USE_VIRTUALENV/bin/activate ] && . $SALT_USE_VIRTUALENV/bin/activate

exec salt-minion

